### PR TITLE
Don't reuse global headers for JSON parts

### LINKED ISSUE #216: Bug in RequestFactory for multipart requests
Hi, 
This PR #176 introduced a bug when using the multipart factory, the global `Content-Type` header is forced to `application/json` causing the request parser to fail with this stack:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (BufferedInputStream); line: 1, column: 10] (through reference chain: graphql.servlet.internal.GraphQLRequest["query"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:675)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:40)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:369)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1188)
	at graphql.servlet.GraphQLObjectMapper.readGraphQLRequest(GraphQLObjectMapper.java:65)
	at graphql.servlet.AbstractGraphQLHttpServlet.lambda$init$4(AbstractGraphQLHttpServlet.java:212)
	at graphql.servlet.AbstractGraphQLHttpServlet.doRequest(AbstractGraphQLHttpServlet.java:309)
	at graphql.servlet.AbstractGraphQLHttpServlet.doRequestAsync(AbstractGraphQLHttpServlet.java:300)
	at graphql.servlet.AbstractGraphQLHttpServlet.doPost(AbstractGraphQLHttpServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
```

This PR #215 fixes the issue by passing a fresh map of headers for each part instead of using the global one.

### PR DESCRIPTION
**Pull request by ophelie**
This PR https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/176 introduced a bug where the global `Content-Type` header for multipart requests was forced to `application/json;charset=UTF-8` instead of `multipart/form-data`. This makes the query parser fail.

This fixes #216

### CODE REVIEW

File: graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java [hunk 1]
```diff
@@ -19,8 +19,8 @@ private RequestFactory() {
     static HttpEntity<Object> forMultipart(String query, String variables, HttpHeaders headers) {
         headers.setContentType(MediaType.MULTIPART_FORM_DATA);
```
Comment (oliemansm) [inline graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java]: It's setting the Content-Type header explicitly to `MULTIPART_FORM_DATA` here, so it should be good actually.

File: graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java [hunk 2]
```diff
@@ -19,8 +19,8 @@ private RequestFactory() {
...
         LinkedMultiValueMap<String, Object> values = new LinkedMultiValueMap<>();
-        values.add("query", forJson(query, headers));
-        values.add("variables", forJson(variables, headers));
+        values.add("query", forJson(query, new HttpHeaders()));
```
Comment (oliemansm) [inline graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java]: This overrides any customization people would want to do with the headers, and shouldn't be necessary seeing my comment above. So would assume the cause of your particular problem is somewhere else.

File: graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java (hunk 1 above)
Comment (ophelie) [reply graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java]: Nope because you pass the same map of headers to the `forJson` method which overrides the `Content-Type` header to `application/json`.

File: graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java (hunk 2 above)
Comment (ophelie) [reply graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java]: Mmh I assume people would want to customize the general headers to pass authentication for instance, which they still can. It's not that common to have the need to customize the sub-parts of the request IMO.

File: graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java (hunk 1 above)
Comment (oliemansm) [reply graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java]: I'll have to see how these methods are being used exactly then to understand what you mean. Because in that case it sounds like the parameter `header` should be removed from this method entirely.

Comment (oliemansm) [reply graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java]: Can you share your test code where you use this to demonstrate the problem you're facing here? Because `GraphQLTestTemplate.postMultipart` only updates the content-type header here just before it uses `restTemplate.exchange`, so that should be good imo. `forJson` does exactly the same. So when you call `forJson` first followed by `forMultipart` or the other way around from your tests I'd expect it to work properly. The problem you have that led you to this solution is not clear to me now.

Comment (ophelie) [reply graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java]: The test code does nothing fancy, a simple call to `graphQLTestTemplate.postMultipart()` triggers the error. I don't use the factory methods from `RequestFactory` since they are package private.

The problem is `graphQLTestTemplate.postMultipart()` calls the factory method `RequestFactory.forMultipart` which in turns calls the factory method `RequestFactory.forJson` with the same map of headers, which overrides the `Content-Type` set in `RequestFactory.forMultipart`.

Comment (oliemansm) [reply graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java]: Ah, I totally missed it was calling the `forJson` from within the `forMultipart` method.
